// Copies vendor stylesheets for the preview frame and generates every file
// that depends on the security headers (preview pages, .htaccess, nginx, Caddy).
import { mkdirSync, copyFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  CSP_APP, PREVIEW_VARIANTS, cspPreview, metaPolicy, headerPolicy, COMMON_HEADERS, HSTS,
} from './security.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pub = join(root, 'public');
const vendor = join(pub, 'preview', 'vendor');
mkdirSync(vendor, { recursive: true });
mkdirSync(join(root, 'deploy'), { recursive: true });

const copies = {
  'github-markdown-light.css': 'node_modules/github-markdown-css/github-markdown-light.css',
  'github-markdown-dark.css': 'node_modules/github-markdown-css/github-markdown-dark.css',
  'hljs-light.css': 'node_modules/highlight.js/styles/github.min.css',
  'hljs-dark.css': 'node_modules/highlight.js/styles/github-dark.min.css',
  '../preview.css': 'src/styles/preview.css',
};
for (const [name, src] of Object.entries(copies)) copyFileSync(join(root, src), join(vendor, name));

const GENERATED = 'Generated by scripts/prepare-assets.mjs from scripts/security.mjs. Do not edit by hand.';

// Preview documents. They contain no scripts; the app fills #content from outside.
for (const variant of PREVIEW_VARIANTS) {
  const html = `<!doctype html>
<!-- ${GENERATED} -->
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="${metaPolicy(cspPreview(variant))}">
<meta name="referrer" content="no-referrer">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Preview</title>
<link rel="stylesheet" href="vendor/github-markdown-light.css" id="theme-md-light">
<link rel="stylesheet" href="vendor/github-markdown-dark.css" id="theme-md-dark" disabled>
<link rel="stylesheet" href="vendor/hljs-light.css" id="theme-hl-light">
<link rel="stylesheet" href="vendor/hljs-dark.css" id="theme-hl-dark" disabled>
<link rel="stylesheet" href="preview.css">
</head>
<body>
<article class="markdown-body" id="content"></article>
</body>
</html>
`;
  writeFileSync(join(pub, 'preview', variant.file), html);
}

// ---------- Apache / LiteSpeed (.htaccess) — used on shared hosting such as FastComet
const q = (s) => s.replace(/"/g, '\\"');
const headerLines = (headers, indent = '  ') =>
  Object.entries(headers).map(([k, v]) => `${indent}Header always set ${k} "${q(v)}"`).join('\n');

const htaccess = `# ${GENERATED}
# Markdown Preview Editor — static site. No server-side code runs here.

Options -Indexes -MultiViews
DirectoryIndex index.html
AddDefaultCharset utf-8
AddType text/javascript .js .mjs
AddType text/css .css
AddType image/svg+xml .svg

# Force HTTPS so nobody on the network can tamper with the site's code.
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP:X-Forwarded-Proto} !=https
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>

<IfModule mod_headers.c>
  # Browsers ignore HSTS on plain HTTP, so it is safe to always send it.
  Header always set Strict-Transport-Security "${HSTS}"
${headerLines(COMMON_HEADERS)}

  <FilesMatch "^(index\\.html)?$">
    Header always set Content-Security-Policy "${q(headerPolicy(CSP_APP))}"
    Header always set X-Frame-Options "DENY"
    Header always set Cache-Control "no-cache"
  </FilesMatch>
${PREVIEW_VARIANTS.map((v) => `
  <FilesMatch "^${v.file.replace('.', '\\.')}$">
    Header always set Content-Security-Policy "${q(headerPolicy(cspPreview(v)))}"
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set Cache-Control "no-cache"
  </FilesMatch>`).join('')}

  # Hashed build files never change, cache them for a year.
  <FilesMatch "-[A-Za-z0-9_-]{8,}\\.(js|css)$">
    Header always set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
</IfModule>

# Nothing but the site files may be served.
<FilesMatch "^\\.|\\.(md|map|txt|zip|bak|log|sh|mjs|ts|json)$">
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
</FilesMatch>
<FilesMatch "^SHA256SUMS\\.txt$">
  <IfModule mod_authz_core.c>
    Require all granted
  </IfModule>
</FilesMatch>
`;
writeFileSync(join(pub, '.htaccess'), htaccess);

// ---------- nginx
const ngx = (headers, indent) =>
  Object.entries(headers).map(([k, v]) => `${indent}add_header ${k} "${v}" always;`).join('\n');
const commonNgx = (indent) => `${ngx(COMMON_HEADERS, indent)}\n${indent}# Uncomment once the site is served over HTTPS:\n${indent}# add_header Strict-Transport-Security "${HSTS}" always;`;

const nginx = `# ${GENERATED}
# Serves the static build. Put TLS termination in front of it (or add a
# 443 server block) for production use.
server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;
    charset utf-8;

    # add_header in a location replaces inherited ones, so every location
    # repeats the full set.
    location = / {
${commonNgx('        ')}
${ngx({ 'Content-Security-Policy': headerPolicy(CSP_APP), 'X-Frame-Options': 'DENY', 'Cache-Control': 'no-cache' }, '        ')}
        try_files /index.html =404;
    }
    location = /index.html {
${commonNgx('        ')}
${ngx({ 'Content-Security-Policy': headerPolicy(CSP_APP), 'X-Frame-Options': 'DENY', 'Cache-Control': 'no-cache' }, '        ')}
    }
${PREVIEW_VARIANTS.map((v) => `    location = /preview/${v.file} {
${commonNgx('        ')}
${ngx({ 'Content-Security-Policy': headerPolicy(cspPreview(v)), 'X-Frame-Options': 'SAMEORIGIN', 'Cache-Control': 'no-cache' }, '        ')}
    }`).join('\n')}
    location /assets/ {
${commonNgx('        ')}
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }
    location ~ /\\. { deny all; }
    location / {
${commonNgx('        ')}
        try_files $uri =404;
    }
}
`;
writeFileSync(join(root, 'deploy', 'nginx.conf'), nginx);

// ---------- Caddy
const caddyHeaders = (headers, indent) =>
  Object.entries(headers).map(([k, v]) => `${indent}${k} "${v}"`).join('\n');
const caddy = `# ${GENERATED}
# Replace the address with your domain; Caddy obtains an HTTPS certificate automatically.
{$SITE_ADDRESS:markdown.example.com} {
    root * /srv
    encode zstd gzip
    file_server

    header {
${caddyHeaders({ ...COMMON_HEADERS, 'Strict-Transport-Security': HSTS, '-Server': '' }, '        ').replace('-Server ""', '-Server')}
    }

    @app path / /index.html
    header @app {
${caddyHeaders({ 'Content-Security-Policy': headerPolicy(CSP_APP), 'X-Frame-Options': 'DENY', 'Cache-Control': 'no-cache' }, '        ')}
    }
${PREVIEW_VARIANTS.map((v) => `
    @${v.file.replace('.html', '').replace('-', '_')} path /preview/${v.file}
    header @${v.file.replace('.html', '').replace('-', '_')} {
${caddyHeaders({ 'Content-Security-Policy': headerPolicy(cspPreview(v)), 'X-Frame-Options': 'SAMEORIGIN', 'Cache-Control': 'no-cache' }, '        ')}
    }`).join('\n')}

    @hidden path /.*
    respond @hidden 404
}
`;
writeFileSync(join(root, 'deploy', 'Caddyfile'), caddy);

console.log('prepare-assets: preview pages, .htaccess, nginx.conf and Caddyfile generated');
